openapi: 3.0.0
info:
  title: My API
  description: Description of my API
  version: 1.0.0
  contact:
    name: My Name
    email: email@email.com
servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local server
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      version:
        enum:
          - v1
          - v2
        default: v1
components:
  securitySchemas:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Dummy Homepage
      summary: Get example data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
        '400':
          description: Bad request
        '500':
          description: Internal server error
